import path from 'path';
import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';
import webExtension from '@samrum/vite-plugin-web-extension';
import eslint from 'vite-plugin-eslint';
import { getManifest } from './src/manifest';

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
    const env = loadEnv(mode, process.cwd(), '');

    return {
        plugins: [
            react({
                include: ['**/*.jsx', '**/*.js'],
            }),
            eslint(),
            webExtension({
                manifest: getManifest(Number(env.MANIFEST_VERSION), env.BROWSER_TARGET, env),
                // Adds the use_dynamic_url property to web accessible resources generated by the plugin.
                // In Firefox Manifest 3 (experimantel): Set to false
                // (default: true)
                useDynamicUrlWebAccessibleResources: true,
                // In Manifest V3, merge web accessible resource definitions that have matching non-resource properties and dedupe and sort resources.
                // In Manifest V2, sort web accessible resources.
                // (default: true)
                optimizeWebAccessibleResources: true,
            }),
        ],
        resolve: {
            alias: {
                '~': path.resolve(__dirname, './src'),
            },
        },
    };
});
